#!/bin/sh
set -e

lb config noauto \
  --distribution trixie \
  --architectures amd64 \
  --archive-areas "main contrib non-free non-free-firmware" \
  --debian-installer live \
  --debian-installer-gui true \
  --bootappend-live "boot=live components quiet splash" \
  --binary-images iso-hybrid \
  --iso-application "Vanilla Linux" \
  --iso-publisher "Vanilla Linux" \
  --iso-volume "VANILLA_LINUX" \
  --memtest none \
  --apt-recommends true
