#!/bin/sh
set -e

lb config \
  --distribution trixie \
  --architectures amd64 \
  --archive-areas "main contrib non-free non-free-firmware" \
  --debian-installer live \
  --debian-installer-gui true \
  --bootappend-live "boot=live components quiet splash" \
  --binary-images iso-hybrid \
  --iso-application "Debian XFCE Remix" \
  --iso-publisher "Carson / Debian XFCE Remix" \
  --iso-volume "DEBIAN_XFCE" \
  --memtest none \
  --apt-recommends true
